name: best_matcher
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.4.5
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  provider: ^6.0.0
  english_words: ^4.0.0
  flutter_dotenv: ^5.0.0
  carousel_slider: ^4.2.1
  image_network: ^2.5.1
  firebase_messaging: ^14.4.1
  grouped_list: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  cloud_firestore: ^4.4.5
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  english_words: ^4.0.0
  provider: ^6.0.01
  grouped_list: ^5.1.2
  flutter_lints: ^2.0.0
  carousel_slider: ^4.2.1
  fake_cloud_firestore: ^2.4.1
  flutter_dotenv: ^5.0.0
  image_network: ^2.5.1
  firebase_messaging: ^14.4.1

flutter:
  uses-material-design: true
